### ISSUE TITLE
Error while running standard area-negative chart

### ISSUE THREAD

**Issue by grrakesh4769** [grrakesh4769/highcharts-serverside-export#8]
Trace:
org.mozilla.javascript.EcmaError: TypeError: Cannot find function replace in object 86.83333333333333. (env.rhino.1.2.35.js#8139)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3951)
	at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3929)
	at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3962)
	at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3981)
	at org.mozilla.javascript.ScriptRuntime.notFunctionError(ScriptRuntime.java:4053)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThisHelper(ScriptRuntime.java:2425)
	at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2407)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1322)
	at script(env.rhino.1.2.35.js:8139)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ScriptableObject$GetterSlot.getValue(ScriptableObject.java:312)
	at org.mozilla.javascript.ScriptableObject.get(ScriptableObject.java:472)
	at org.mozilla.javascript.IdScriptableObject.get(IdScriptableObject.java:334)
	at org.mozilla.javascript.ScriptableObject.getProperty(ScriptableObject.java:2269)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1514)
	at org.mozilla.javascript.ScriptRuntime.getObjectProp(ScriptRuntime.java:1507)
	at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:1240)
	at script(highcharts.src.js:11380)
	at script(highcharts.src.js:12031)
	at script(highcharts.src.js:10933)
	at script(data.src.js:810)
	at script(highcharts.src.js:609)
	at script(highcharts.src.js:10856)
	at script(highcharts.src.js:10833)
	at script.renderSVGFromObject(svg-renderer-highcharts.js:9)
	at script.renderSVGFromJson(svg-renderer-highcharts.js:16)
	at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:815)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:109)
	at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
	at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:3282)
	at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:107)
	at org.mozilla.javascript.Context$1.run(Context.java:490)
	at org.mozilla.javascript.Context.call(Context.java:501)
	at org.mozilla.javascript.Context.call(Context.java:488)
	at org.mozilla.javascript.ScriptableObject.callMethod(ScriptableObject.java:2609)
	at gr.highcharts.export.HighchartsSVGGenerator$2.run(HighchartsSVGGenerator.java:99)
	at org.mozilla.javascript.Context.call(Context.java:501)
	at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:503)
	at gr.highcharts.export.HighchartsSVGGenerator.generateChartSvg(HighchartsSVGGenerator.java:94)
	at gr.highcharts.export.HighchartsSVGGenerator.generateChartSvg(HighchartsSVGGenerator.java:114)
	at gr.highcharts.export.HighchartsChart.updateSVG(HighchartsChart.java:49)
	at gr.highcharts.export.HighchartsChart.<init>(HighchartsChart.java:42)
	at gr.highcharts.export.Main.main(Main.java:24)
Exception in thread "main" java.lang.NullPointerException
	at java.io.StringReader.<init>(StringReader.java:50)
	at gr.highcharts.export.HighchartsChart.storeAsImage(HighchartsChart.java:74)
	at gr.highcharts.export.HighchartsChart.storeAsImage(HighchartsChart.java:103)
	at gr.highcharts.export.Main.main(Main.java:24)

**Comment by grrakesh4769** [comment]
Issue occurs from these lines :
` get offsetWidth(){
        return Number((this.style.width || '').replace("px",""));
    }`
from env.rhino.1.2.35.js;
Seemingly width is a number and not an string object
